### ISSUE TITLE
unexpected server response (400) 

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode-edge-debug#1] opened 2016-04-26 17:57 UTC
Hello,

i have an issue
When i config the launch.json with the attach script and i want to attach the file i got an error:

```
›Warning: Found more than one valid target page. Attaching to the first one. Available pages: ["about:start","https://www.msn.com/spartan/dhp?locale=de-DE&market=DE"]` and `[debugger-for-chrome] unexpected server response (400)
```

The Config:

```
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Attach with sourcemaps",
            "type": "edge",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true
        },
        {
            "name": "Attach to url with files served from ./out",
            "type": "edge",
            "request": "attach",
            "port": 9222,
            "webRoot": "${workspaceRoot}/out"
        }
    ]
}
```

**Comment by andysterland** [comment] 2016-04-26 18:08
Is your page already running? From the list it looks you have the start page and MSN to attach to. If you have just your page open that you want to attach to that should work better. Or, you can add a `url` property to your config with the exact (there is no fuzzy matching) URL in the browser that you want to attach too.

**Comment by ghost** [comment] 2016-04-26 18:18
Now i have this error: `[debugger-for-chrome] unexpected server response (400)`

**Comment by andysterland** [comment] 2016-04-26 18:35
Yay progress :). 

Could you add the setting `"diagnosticLogging": true` to your launch.json's attach section and see if that gives any more error details that you can paste here.

**Comment by ghost** [comment] 2016-04-26 18:46
```
OS: win32 ia32
  ›Node version: v5.10.0
  ›Adapter version: 0.0.5
  ›initialize({"adapterID":"edge","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true})
  ›attach({"name":"Launch localhost with sourcemaps","type":"edge","request":"launch","url":"http://localhost/my.html","webRoot":"c:\\Users\\Malte\\Desktop\\Edge","sourceMaps":true,"diagnosticLogging":true,"noDebug":false,"port":9222})
  ›Attempting to attach on port 9222

  ›Adapter error: Error: Command failed: C:\Users\Malte\.vscode-insiders\extensions\msjsdiag.debugger-for-edge-0.2.0\node_modules\edge-diagnostics-adapter\dist\x64\EdgeDiagnosticsAdapter.exe --port=9222 --launch=http://localhost/my.html
[2016-04-26 20:43:42] [error] Handshake ended with HTTP error: 400
  ›From client: disconnect({"restart":false})
  ›To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}


```

**Comment by andysterland** [comment] 2016-04-26 19:30
Thanks. Could you try running from a console window:
`C:\Users\Malte\.vscode-insiders\extensions\msjsdiag.debugger-for-edge-0.2.0\node_modules\edge-diagnostics-adapter\dist\x64\EdgeDiagnosticsAdapter.exe --chrome` from the command line then navigate to `localhost:9222` and click on the page you want to debug. Then hopefully they'll be some more detailed info in the console. Ideally if you navigate to localhost:9222 from Chrome.

**Comment by andysterland** [comment] 2016-04-27 00:02
I updated the title of the issue to reflect the bug a bit better.

**Comment by andysterland** [comment] 2016-04-27 19:03
@Nalyienf random question: are you using a version of Windows that isn't en-us?

**Comment by ghost** [comment] 2016-04-29 11:48
Yes and the console option doesnt work. 
I tried the option  "Launch localhost with sourcemaps". ( I use XAMPP) Edge is opening the side but in the console is an error: `›Warning: Can't find a page with url: http://localhost/index.html. Available pages: ["unknown"]` and on the top of VSCode `[debugger-for-chrome] unexpected server response (400)`

I tried it also with the Chrome Debugger an all worked fine.

**Comment by andysterland** [comment] 2016-04-29 16:57
Ahh yea I think the issue is:
https://github.com/Microsoft/edge-diagnostics-adapter/issues/19

Basically that the ACL isn't being applied to the folder in non-English builds.

**Comment by ghost** [comment] 2016-04-29 17:52
It worked with "Launch localhost with sourcemaps" 
   THANK YOU ! :)

**Comment by ghost** [comment] 2016-04-29 18:19
Only when i debug with "Launch index.html" i get an error `[debugger-for-chrome] Got response from target app, but no valid target pages found`.

But with the chrome debugger this option works.

**Comment by andysterland** [comment] 2016-05-06 21:22
That error means that the URL in the launch.json doesn't match the URLs that are open in the browser. I'm going to close this issue as the issue should be fixed. If you have problems launching please do open a new issue with more details :). Thanks for trying it out!

**Closed as completed by andysterland** 2016-05-06 21:22 UTC
